version: '3'
services:
  mysql-standalone:
    image: 'mysql'
    environment:
      - MYSQL_ROOT=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=managerM
    ports:
      - "3307:3307"
  springboot-docker-container:
    image: akjalan/springboot-docker-container
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/managerM?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD:
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone
